name: Kali SSH Stable

on:
  workflow_dispatch:

jobs:
  kali:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Setup Kali environment
        run: |
          sudo apt update
          sudo apt install -y docker.io

          docker run -d --name kali \
            kalilinux/kali-rolling sleep infinity

      - name: Install tools in Kali
        run: |
          docker exec kali apt update
          docker exec kali apt install -y \
            nmap netcat-traditional python3 git curl nano

      - name: Start interactive shell (tmate host)
        uses: mxschmitt/action-tmate@v3

      - name: Keep alive
        run: |
          while true; do
            echo "Kali container running..."
            sleep 60
          done
