name: Kali Linux SSH Container

on:
  workflow_dispatch:

jobs:
  kali:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    container:
      image: kalilinux/kali-rolling

    steps:
      - name: Update Kali
        run: |
          apt update
          apt install -y \
            sudo curl wget git nano tmux htop \
            openssh-client net-tools iproute2 \
            python3 python3-pip \
            nmap netcat-traditional

      - name: Clean terminal
        run: |
          touch ~/.hushlogin
          clear

      - name: Start SSH (tmate)
        uses: mxschmitt/action-tmate@v3

      - name: Keep alive
        run: |
          while true; do
            echo "[KALI RUNNING]"
            sleep 60
          done
