name: Kali Linux SSH

on:
  workflow_dispatch:

jobs:
  kali:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Start Docker
        run: |
          docker pull kalilinux/kali-rolling

      - name: Run Kali container
        run: |
          docker run -d --name kali \
            kalilinux/kali-rolling sleep infinity

      - name: Install tools in Kali
        run: |
          docker exec kali apt update
          docker exec kali apt install -y \
            nmap netcat-traditional curl wget git python3 nano 
          

      - name: Open SSH (tmate)
        run: |
          sudo apt update
          sudo apt install -y tmate
          sudo snap install zellij

          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready

          echo "SSH INTO KALI HOST:"
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'

      - name: Keep alive
        run: |
          while true; do
            echo "Kali container running..."
            sleep 60
          done
