name: Windows SSH (Working Method)

on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: System info
        shell: pwsh
        run: |
          systeminfo
          whoami

      - name: Start SSH session
        uses: mxschmitt/action-tmate@v3
